### ISSUE TITLE
Consolidate Multiple Storage Devices into One

### ISSUE THREAD

**Issue by Ryushin** [slawern/hddled#1]
I have a Thinkpad P17 Gen2 with three storage devices.  It would be nice to have an option to specify which storage devices to query along with an option to consolidate multiple devices into a single activity led.  Right now having 3 tray icons takes a lot of space.

BTW, thank you for writing this.  This is exactly what I needed.

**Comment by slawern** [comment]
Thank you for the feedback. Both of your suggestions are on my TODO list. I hope, I will implement them soon.

**Comment by slawern** [comment]
I've added the `-x` option which can be used to exclude a device (or a group of devices) from monitoring. E.g.

`-x sr`

will exclude CDROM drives (`/dev/sr*`).
The option can be used more than once to exclude different devices.

The `-c` (consolidate) option will be implemented soon.

**Comment by slawern** [comment]
`-c`  (combine) option is now available.
